### ISSUE TITLE
Replace Action OnSave with event

### ISSUE THREAD

**Issue by miyconst** [Starcounter/InvoiceDemo#19]
C# has native event handlers, and they should be used instead of `Action`s.

The result would look similar to:
```cs
public event EventHandler Saved;
```

```cs
page.Saved += (s, a) => { 
    ((InvoicesPage)master.RecentInvoices).RefreshData();
};
```

**Comment by warpech** [comment]
Good idea. Could you update the source at the text on starcounter.io?

**Comment by miyconst** [comment]
Did you mean "update the source **and** the text on starcounter.io"?

**Comment by warpech** [comment]
Yes :hushed:

**Comment by miyconst** [comment]
Sure. Assigning to myself.

**Comment by warpech** [comment]
@miyconst now, that I know more about `Action`s and `Event`s in C#, I think that Action is actually more appropriate. Could you elaborate on why did you think otherwise?

**Comment by miyconst** [comment]
- An `Action` is a variable, means only one reference to a function. An `event` can have multiple subscribers.
- It is impossible to provide parameter names in `Action` and `Func`, which means difficult code to read and constant question what is which parameter state for.

**Comment by warpech** [comment]
> An `Action` is a variable, means only one reference to a function. An `event` can have multiple subscribers.

I think that a single subscriber is usually a better pattern. Only the parent controls the nested page and gets feedback from it.

For me the only problem with `Action` is that it is easy to overwrite the callback by mistake. With `Event` this doesn't happen.

> It is impossible to provide parameter names in `Action` and `Func`, which means difficult code to read and constant question what is which parameter state for.

Can you provide some example? 

What I dislike about `Event` is that it requires more code to pass arguments. You need to create your own class for the arguments, which extends `EventArgs`. Or is there a simpler pattern?

With `Action` it is super simple to pass arguments. Like here:

Declaration: https://github.com/StarcounterSamples/People/blob/af0dacee05dcd9830a2f40202f7f513c13c1d9e3/src/People/ViewModels/MembersListPage.json.cs#L8

Usage: https://github.com/StarcounterSamples/People/blob/develop/src/People/ViewModels/OrganizationPage.json.cs#L22https://github.com/StarcounterSamples/People/blob/develop/src/People/ViewModels/OrganizationPage.json.cs#L22

@Joltrix is now applying Action/Event in People app, I would like to guide him what is the "correct" way and stick to that. Then he will describe the pattern in http://starcounter.io/cookbook/

**Comment by Mnosek** [comment]
I think that the correct pattern depends on the particular situation. Event requires more code to write, but it is easier to maintain and change without changing of the event signature (by extending and changing EventArgs). If the only thing we need is to prevent controlling parent page by children - action seems to be good enough. If the action/event has more global meaning (could be possibly subscribed by sth external), the event is more suitable. In situation that @warpech quoted, the Action looks appropriate IMO.

Anyway, I would consider the name of the actions. For me OnDelete/HasBeenDeleted feels more clear.

**Comment by Mnosek** [comment]
Thanks @miyconst for extended reply. I've analysed it a bit more and I can agree that the events are more suitable especially if the whole app is very complex. Making any changes in events are much easier.

Anyway, if the purpose of using action/event is that we don't want to allow nested page to control parent page and especially if everything is placed in one file - actions look good enough for me.

I don't want to raise up a pattern/good practices discussion, because there is never one answer for a topic.
