### ISSUE TITLE
Create code for InvoiceDemo3

### ISSUE THREAD

**Issue by warpech** [Starcounter/InvoiceDemo#21]
Create InvoiceDemo3 (first on a separate branch, then merge to `master`), with the following features:

- minimum code changes from InvoiceDemo2
- able to run in Launcher as well as standalone
- ~~uses Simplified data model instead of its own~~ integrates with Simplified data model
- able to look up Organizations and Products (similarly to Procurement)

Layout editing is out of scope of this task

**Comment by warpech** [comment]
Initial version posted on https://github.com/Starcounter/InvoiceDemo/tree/launcherintegration branch. Requires further work.

**Comment by miyconst** [comment]
- [x] Able to run in Launcher as well as standalone.
- [ ] ~~Uses Simplified data model instead of its own.~~
- [ ] Able to look up Organizations and Products (similarly to Procurement).

**Comment by warpech** [comment]
Thanks! Merged to master.

To satisfy the criteria "minimum code changes from InvoiceDemo2", could you propagate the changes in `style.css` to InvoiceDemo 1 and 2? I mean only the changes in following declarations:

- `.invoicedemo button:hover`
- `.invoicedemo .invoice-item-cell a:link`

Do you think there are any more changes that should be propagated to InvoiceDemo 1 & 2?

**Comment by miyconst** [comment]
Yes, I think that the section
```html
<!-- Trigger button handlers on click -->
```
should be wrapped in a `div`.

**Comment by miyconst** [comment]
>- `.invoicedemo button:hover`
- `.invoicedemo .invoice-item-cell a:link`

Propagated to InvoiceDemo1 & InvoiceDemo2.

**Comment by warpech** [comment]
Thanks!
