### ISSUE TITLE
Create tutorial for InvoiceDemo3

### ISSUE THREAD

**Issue by warpech** [Starcounter/InvoiceDemo#22]
Should be done in http://starcounter.io/tutorials/, after https://github.com/Starcounter/InvoiceDemo/issues/21 is finished

**Comment by miyconst** [comment]
@warpech is this task on me?

**Comment by warpech** [comment]
Now it is :) This can take few days

**Comment by miyconst** [comment]
We should also add some info about public folder bug (https://github.com/Starcounter/Starcounter/issues/2752) to the tutorial until that's fixed.

**Comment by warpech** [comment]
^ created a separate issue for the above problem

**Comment by miyconst** [comment]
The first version is available here: http://starcounter.io/tutorials/invoicedemo-part-3/

**Comment by miyconst** [comment]
@warpech could you please take a look?

**Comment by warpech** [comment]
1. Add a link to http://starcounter.io/tutorials/invoicedemo-part-3/ in http://starcounter.io/tutorials/
2. In http://starcounter.io/tutorials/invoicedemo-part-3/3-4-add-launcher-menu-item/ (and later pages) please use proper letter case for acronyms and proper nouns (HTML, Bootswatch Paper, Glyphicons, JSON, GET handler)
3. We don't use the word "Polyjuice" to explain features. I changed the text of http://starcounter.io/tutorials/invoicedemo-part-3/
4. I added some introduction in http://starcounter.io/tutorials/invoicedemo-part-3/3-2-run-invoicedemo-inside-launcher/

I think this is good to consider the tutorial done. Incremental updates to the tutorial can be tracked as separate issues.

Can you please fix points 1 & 2 and close the issue? Thanks!

**Comment by miyconst** [comment]
1 & 2, fixed.
3 & 4, good points, thank you.
