### ISSUE TITLE
Inform in the tutorial that server restart is needed

### ISSUE THREAD

**Issue by warpech** [Starcounter/InvoiceDemo#23]
As mentioned in https://github.com/Starcounter/InvoiceDemo/issues/22#issuecomment-114222302, InvoiceDemo tutorial needs to mention in the first page of InvoiceDemo2 and 3 that server needs to be killed if another part of InvcoideDemo is already running.

Two reasons for that:

1. [Public web folders are not updated after an app stops](https://github.com/Starcounter/Starcounter/issues/2752)
2. `An application with the given name is already running. Name "InvoiceDemo". (ScErrApplicationAlreadyRunning (SCERR10036))` (see the below screenshot)

![already running](https://cloud.githubusercontent.com/assets/566463/8290934/59ecc230-1926-11e5-984a-e06829ae8c6d.png)

When https://github.com/Starcounter/Starcounter/issues/2752 is fixed, it may be enough to stop InvoiceDemo in Administrator before trying another part of the demo.

**Comment by miyconst** [comment]
Added some text: http://starcounter.io/tutorials/2-1-introduction-to-part-2/

I wanted to be short, but in the end it is very long, don't know how to shorten it ((

**Comment by warpech** [comment]
Thanks, I will make it shorter

**Comment by warpech** [comment]
I made it shorter: http://starcounter.io/tutorials/2-1-introduction-to-part-2/
And created a new page, to which I copied the explanation that the app names must be unique: http://starcounter.io/guides/tools/starting-and-stopping-apps/

**Comment by miyconst** [comment]
:+1:
