### ISSUE TITLE
Migrate to Polymer 1.1

### ISSUE THREAD

**Issue by tomalec** [Starcounter/InvoiceDemo#24]
- [x] InvoiceDemo1
 - [x] InvoiceDemo2
 - [x] InvoiceDemo3

**Comment by tomalec** [comment]
Changes are being made at [polymer_1.0 branch](https://github.com/Starcounter/InvoiceDemo/tree/polymer_1.0)

**Comment by tomalec** [comment]
The only things left are to remove the need of id reference
```html
<template is="dom-bind" id="InvoicePage">
        <dom-bind-notifier ref="InvoicePage" 
```
and test in Launcher once Launcher is migrated to Polymer as well.

**Comment by tomalec** [comment]
There is quite big issue with data flow if we would like to use :
```html
<template is="dom-bind">
..
</template>
<dom-bind-notifier>
<puppet-client>
```
As puppet-client provides model asynchronously, and dom-bind-notifier needs to observe object that is not yet there.

@warpech Please let me know, when you will have time to discuss it. As we need to decide what is in fact expected behavior.

**Comment by warpech** [comment]
Me and @tomalec discussed it a bit yesterday. 

Using the fact that PuppetJs creates the JavaScript data object in the constructor, not on receiving the response may be a hint to solving the problem. @tomalec said he will evaluate that.

**Comment by tomalec** [comment]
After small fix in puppet-client it helped. But now we have another problem for `<dom-bind-notifier>` outside of dom-bind - it's not notified when entire model get's changed

**Comment by warpech** [comment]
I thought that this is solved using `observe` property in Polymer, doesn't it? Like here: https://github.com/winhowes/file-tree/blob/d19a248df66becc9598138ab874b5798414237b7/file-tree.html#L50

**Comment by tomalec** [comment]
But this is not 'ours' Polymer element
so we cannot set such property in definition of dom-bind.

**Comment by tomalec** [comment]
It seems the only way is making it rely on implementation detail of `dom-bind`, e.g. relying of a fact that `dom-bind` stamps it's content before itself:
```html
<template is="dom-bind">
    blah blah...
    <dom-bind-notifier path="model" observed-object="{{model}}" deep></dom-bind-notifier>
</template>
```

**Comment by tomalec** [comment]
Another solution that cam into my mind is plugin in such observers to `dom-bind` from `dom-bind-notifier` code like:
```js
// attached or refChanged: function(){
   var domBindNotifier = this;
   // add dom-bind-notifier specific method to dom-bind instance
    domBind.notifyDomBindNotifier = function(oldVal, newVal){
        domBindNotifier.observedObjectChanged(oldVal, newVal);
    };
    // attach Polymer-observable property
    domBind.properties[ domBindNotifier.path ]= {
        type: Object,
        observer: 'notifyDomBindNotifier'
    };
```

Thanks to that we could write:
```html
<template is="dom-bind">
   blah blah ...
</template>
...
 <dom-bind-notifier path="model" deep></dom-bind-notifier>
```

Brief check shows it works, but it's quite hacky as well, and there is no warranty that attaching properties will work in run-time, plus attaching nested object might be a problem.

**Comment by tomalec** [comment]
Even if using `domBind.properties` seems to work in isolated case, it will not serve nice in our use cases as model (observed-object) is not changed by Polymer using Polymer's protocol, but by Juicy's vanilla imported-template element. And I believe there is no need to introduce Polymer's protocol into `imported-template`. So the only way to get notified, without asking user to do anything magical, is to somehow hijack property setters in `dom-bind` instance - and I would said that's too much of hacking.

@warpech , @miyconst Do you think we can live with:
```html
<template is="dom-bind">
    blah blah...
    <dom-bind-notifier path="model" observed-object="{{model}}" deep></dom-bind-notifier>
</template>
```
?

**Comment by miyconst** [comment]
I am okay with it. In the Polyjuice apps we would use it only once, on the master page, not a big deal.

The 'ref' property is still supported, right?

**Comment by tomalec** [comment]
> The 'ref' property is still supported, right?
Right

**Comment by warpech** [comment]
> I am okay with it. In the Polyjuice apps we would use it only once, on the master page, not a big deal.

@tomalec please confirm - is it only on the master page (LauncherTemplate.html or StandalonePage.html) or on every partial that uses <template is="dom-bind">?

**Comment by tomalec** [comment]
Dom-bind-notifier is needed for every dom-bind so unfortunatelly for every
partial that uses polymer's dom-bind.

However, to reduce amount of Object.observes, we will use
puppet-dom-bind-notfiers that will attach to single puppet-client => single
jsonpatch observer.
11 wrz 2015 09:59 "Marcin Warpechowski" <notifications@github.com>
napisał(a):

**Comment by miyconst** [comment]
>Dom-bind-notifier is needed for every dom-bind so unfortunatelly for every partial that uses polymer's dom-bind.

But it will be the only one root element, we can't nest `dom-bind` inside a `dom-bind`.

**Comment by tomalec** [comment]
Nope there will be more. We cannot nest directly but we will do it
indirectly, via imported templet.
11 wrz 2015 11:24 "Konstantin" <notifications@github.com> napisał(a):

**Comment by miyconst** [comment]
Does this mean, that `dom-bind-notifier` should be included in each partial template?

**Comment by tomalec** [comment]
Yes
11 wrz 2015 13:27 "Konstantin" <notifications@github.com> napisał(a):

**Comment by tomalec** [comment]
[polymer_1.0 branch](https://github.com/Starcounter/InvoiceDemo/tree/polymer_1.0) is ready to be merged.

the only glich that is left is a problem with `<starcounter-debug-aid>` in standalone mode:
https://github.com/Polyjuice/starcounter-debug-aid/issues/35
https://github.com/Juicy/juicy-jsoneditor/issues/5

**Comment by tomalec** [comment]
@warpech, @miyconst We do want to fully support `<s-d-a>` in here, don't we?

**Comment by miyconst** [comment]
I think it would be nice to make it work in shady dom.

**Comment by warpech** [comment]
Definitely `<starcounter-debug-aid>` needs to work in standalone mode. Thanks for making this work!
