### ISSUE TITLE
Consider simplifying auto-updates

### ISSUE THREAD

**Issue by tomalec** [Starcounter/InvoiceDemo#29]
Currently client needs to bump `ClearFoundSomebodies$` and `ClearFoundProducts$` manually.

That requires at least 9 lines of code, some logic on client side, and looks ugly with Polymer 1.0

That's quite a lot just to hide a tooltip on blur.

As server is not aware of blur/keydown events, maybe we can just hide tooltip, and leave data there?

**Comment by warpech** [comment]
Would it be possible to hide the tooltip with just a clever CSS selector? So that we don't have to write client-side code at all?

**Comment by miyconst** [comment]
It is possible to hide/show dropdown on blur with css, but the problem appears when user makes a search for the second time.

Focused input will display the dropdown with old results. So, the result should be cleared anyway. I am looking for some more elegant solution.

**Comment by miyconst** [comment]
So, there are two solutions I like:

Add custom property to the input:
```html
<input type="text" value="{{model.Name$::input}}" placeholder="Type to find" 
                   clear="{{model.ClearFoundSomebodies$::blur}}" onblur="++this.clear;" />
```

Create a custom element which would wrap this logic inside. This solution requires even more code, but is more elegant.

**Comment by warpech** [comment]
I think this looks elegant enough without the custom element. This is a tutorial, so it would be good to not add layers of complexity in it.

**Comment by miyconst** [comment]
Done, starcounter.io also updated.
