### ISSUE TITLE
Redirect not working

### ISSUE THREAD

**Issue by jakubklekota** [Starcounter/InvoiceDemo#30]
Redirect not working for action buttons in InvoiceDemo (cancel, save, delete).

**Comment by alemoi** [comment]
Thank you for your question Jacub! We will check by setting up redirects to action buttons!

**Comment by warpech** [comment]
This looks like a Polymer 1.1 problem with `puppet-redirect`. @tomalec can you take a look?

**Comment by tomalec** [comment]
Thanks @jakubklekota
It was just wrong Polymer binding inside dom-bind.

**Comment by warpech** [comment]
Any idea why Polymer [says](https://www.polymer-project.org/1.0/docs/devguide/data-binding.html):

> In the vast majority of cases, binding data to other elements should use property binding described above, where changes are propagated by setting the new value to the JavaScript property on the element.

Are we doing something wrong that we (`puppet-redirect`) observe the mutation of Custom Element attributes instead of property?

**Comment by tomalec** [comment]
From what I know it's:
 - performance  of serializing/de-serializing data to attribute (in our case it's just a string)
 - overhead of some Polymer magic, notifiers, lifecycle callbacks etc (not relevant here)
 -  1:1 relation of attribute:property in case of some properties in native elements (we are not native, and this 1:1 may be another performance + maintenance overhead)

vs

 - declarative markup (as mentioned above for some native properties it's given through property as well)

We may consider defining setter/getter.

**Comment by warpech** [comment]
> We may consider defining setter/getter.

These were my thoughts, but actually [vanilla hello-world](https://github.com/webcomponents/hello-world-element/blob/master/hello-world.html) does not use it, nor it is mentioned in https://github.com/webcomponents/gold-standard/wiki
