### ISSUE TITLE
Remove client side logic

### ISSUE THREAD

**Issue by warpech** [Starcounter/InvoiceDemo#34]
There should not be anything like this in client side code

```
document.currentScript.previousElementSibling.concat = function(a, b){
            return a + b;
        };
```

**Comment by miyconst** [comment]
@warpech, should I take this?

**Comment by warpech** [comment]
Yes please

**Comment by miyconst** [comment]
Done. I have also updated a couple of code snippets on starcounter.io to remove horizontal scroll bar.

There is another potential thing to improve: 
https://github.com/Starcounter/InvoiceDemo/blob/master/src/InvoiceDemo3/wwwroot/InvoiceDemo/InvoicePage.html#L17

I think, there should be a workaround to don't use `on-blur="clearFoundSomebodies"` to make it simpler.

**Comment by warpech** [comment]
Perfect, thanks!

> I think, there should be a workaround to don't use on-blur="clearFoundSomebodies" to make it simpler.

There is already an issue for that (https://github.com/Starcounter/InvoiceDemo/issues/29).
