### ISSUE TITLE
You need to use FullName of the database class when querying from Admin UI

### ISSUE THREAD

**Issue by pluppplupp** [Starcounter/InvoiceDemo#36]
In the tutorial step 6 (http://starcounter.io/tutorials/1-introduction-to-part-1/1-6-create-the-database-classes/). The tutorial says, execute query "```SELECT * FROM Invoice```". It doesn't work, you need to inlclude the namespace of the class. "```SELECT * FROM MyNamespace.Invoice```" works.
![2015-12-14_09-59-14](https://cloud.githubusercontent.com/assets/1765023/11776795/488bb37c-a24a-11e5-82d6-2388e69d21a9.png)

**Comment by warpech** [comment]
Related: https://github.com/Starcounter/Starcounter/issues/3178

**Comment by warpech** [comment]
The problem here is that the InvoiceDemo tutorial actually does not use namespaces, but @pluppplupp used namespaces in his recreation of it.

I think that InvoiceDemo should use namespaces to become more realistic.

I discussed this with @per-samuelsson few weeks ago and he agreed.

**Comment by miyconst** [comment]
>I think that InvoiceDemo should use namespaces to become more realistic.

Agree. Even more, I think we should not allow `[Database]` classes without a namespace.

**Comment by warpech** [comment]
> Agree. Even more, I think we should not allow [Database] classes without a namespace.

That's beyond the scope of this issue :)

To fix the problem before https://github.com/Starcounter/Starcounter/issues/3178 is done, I have updated the sample page to include the query with and without namespace.
