### ISSUE TITLE
Put a link to the GitHub repository from the tutorial

### ISSUE THREAD

**Issue by pluppplupp** [Starcounter/InvoiceDemo#37]
The link now is in the header of the first step of the tutorial. But it's not obvious that this points to the GH repro.

![2015-12-14_10-20-27](https://cloud.githubusercontent.com/assets/1765023/11777113/5d7e0792-a24c-11e5-9d44-450a571ce21c.png)

**Comment by warpech** [comment]
Done: http://starcounter.io/tutorials/1-introduction-to-part-1/
