### ISSUE TITLE
Buttons in the demo only works in Chrome

### ISSUE THREAD

**Issue by pluppplupp** [Starcounter/InvoiceDemo#38]
In the later part of the tutorial one cannot click buttons, add row, save changes, cancel changes. Tested in firefox developer edition and Edge browsers. The problem seems to occur in Polymer ```Object.observe``` where observe is not a function.

**Comment by miyconst** [comment]
It should be an easy fix, I take this one.

**Comment by miyconst** [comment]
Fixed, not it works in FF and IE.
