### ISSUE TITLE
When refreshing the demo app, persisted data doesn't load

### ISSUE THREAD

**Issue by pluppplupp** [Starcounter/InvoiceDemo#39]
When I came to the last step of the tutorial and was playing with the demo, when I refreshed the browser the persisted data was not loaded. I thought it was a bug but it's not, the demo app always create a new Invoice when browser refreshes. It's somewhat confusing. 

To make the experience better I suggest adding one more step to make the demo more like a complete app. When refreshing the browser the demo app should load the persisted data.

**Comment by warpech** [comment]
This problem will be solved by adding save and delete notifications:  https://github.com/Starcounter/InvoiceDemo/issues/62

**Comment by warpech** [comment]
Closing this issue, thanks for reporting! It is now tracked in #62
