### ISSUE TITLE
Icons are missing when using debug aid mode

### ISSUE THREAD

**Issue by pluppplupp** [Starcounter/InvoiceDemo#40]
When ctrl-§ debug aid pops up. Icons are missing..

![2015-12-14_10-38-41](https://cloud.githubusercontent.com/assets/1765023/11777476/06e0316e-a24f-11e5-9148-43bdd672cc1a.png)

**Comment by miyconst** [comment]
Taking this one.

**Comment by miyconst** [comment]
Fixed. Should be available with the next nightly build, `> 2.1.836`.
