### ISSUE TITLE
Helper icons used in the turorial, hard to know what they mean

### ISSUE THREAD

**Issue by pluppplupp** [Starcounter/InvoiceDemo#41]
![2015-12-14_10-41-17](https://cloud.githubusercontent.com/assets/1765023/11777544/76cc0840-a24f-11e5-8fbb-9ecbae0739ac.png)
maybe there are other icons out there :)

**Comment by warpech** [comment]
The icons were initially used in GitHub wiki, where there were no better options to capture attention of the reader.

I think that this should be replaced with some better styled sidenotes, similar to what you find in text books (like "... for Dummies").

Some examples of that from Google Images:

![image](https://cloud.githubusercontent.com/assets/566463/11778266/9b287148-a253-11e5-9479-70b3b906de97.png)

![image](https://cloud.githubusercontent.com/assets/566463/11778326/f23e736a-a253-11e5-9482-2b0b39a2c15f.png)

![image](https://cloud.githubusercontent.com/assets/566463/11778365/2af4b930-a254-11e5-8140-d411fe34f51c.png)

**Comment by warpech** [comment]
"For dummies" books do it quite well: http://www.ibm.com/cloud-computing/files/cloud-for-dummies.pdf

**Comment by warpech** [comment]
I reworked the page to have better icons and sidenotes: http://starcounter.io/tutorials/1-introduction-to-part-1/1-6-create-the-database-classes/

WDYT?

If we approve then all other tutorial pages will be updated

**Comment by pluppplupp** [comment]
Looks great :)

**Comment by warpech** [comment]
Now all the tutorials use the sidenotes and "See for yourself" frames as in presented in this example: http://starcounter.io/tutorials/1-introduction-to-part-1/1-6-create-the-database-classes/
