### ISSUE TITLE
Step 6 Pasting the code of the database class, sql statement missing @

### ISSUE THREAD

**Issue by pluppplupp** [Starcounter/InvoiceDemo#45]
![2015-12-14_12-43-47](https://cloud.githubusercontent.com/assets/1765023/11780192/73f15c18-a260-11e5-9614-68d1f327e9e8.png)
The pasted code will generate compile errors.

![2015-12-14_12-46-44](https://cloud.githubusercontent.com/assets/1765023/11780240/c33a4172-a260-11e5-838d-47a3cec1b256.png)

**Comment by miyconst** [comment]
Thanks for noting it.

**Comment by miyconst** [comment]
Fixed. Please next time add link to the page, not only screen shot.

**Comment by pluppplupp** [comment]
Will do!
