### ISSUE TITLE
Got stuck on browser cache in sample app 2

### ISSUE THREAD

**Issue by pluppplupp** [Starcounter/InvoiceDemo#50]
I was continuing from sample app 1 to sample app 2. I got to the step 2-5 (http://starcounter.io/tutorials/2-1-introduction-to-part-2/2-5-links-and-page-morphing/).

I've changed the InvoicesPage.html like the tutorial says, refreshed the browser, hard refresh. But the html page got stuck in cache. 

In chrome it's not enough doing hard reset, you need to go to refresh, right click, and choose "Empty cache and hard reload" or run with developer tools "disable cache" set.
(http://superuser.com/questions/220179/how-can-i-do-a-cache-refresh-in-google-chrome)

Maybe a easy thing in the tutorial would be to have a note about cache.

**Comment by warpech** [comment]
This was fixed with cache fixes in Starcounter: https://github.com/Starcounter/Starcounter/issues/3427
