### ISSUE TITLE
Tutorial Sample app 2 - Step 2-6. Compiler error, missing RedirectUrl

### ISSUE THREAD

**Issue by pluppplupp** [Starcounter/InvoiceDemo#52]
![2015-12-15_10-34-45](https://cloud.githubusercontent.com/assets/1765023/11807075/be95901a-a317-11e5-975b-2eb96073789e.png)

http://starcounter.io/tutorials/2-1-introduction-to-part-2/2-6-delete-an-invoice/

I cannot compile the code when I get to the "That’s it. When you rebuild the program, you will have a functional Delete button"

The ```RedirectUrl``` gets defined in the next step 2-7.

**Comment by warpech** [comment]
Thanks for reporting. 

I removed `RedirectUrl` from step "2.6 Delete an invoice" and added an info at the bottom of the page:

> You may notice a problem that there is no visual indication for the user when an invoice is deleted. We will fix that in the next step by redirecting to the home screen.
