### ISSUE TITLE
Tutorial sample app 2 - Step 3-1. Go to Launcher app

### ISSUE THREAD

**Issue by pluppplupp** [Starcounter/InvoiceDemo#54]
http://starcounter.io/tutorials/invoicedemo-part-3/3-1-install-launcher-from-appstore/

![2015-12-15_11-28-05](https://cloud.githubusercontent.com/assets/1765023/11808158/06431174-a31f-11e5-9686-5dee907d8dc8.png)

Tutorial says " goto localhost:8080", but it should be localhost:8080/Launcher ?

You also need to activate chrome experimental flags.

Launcher app doesn't look like the image in the tutorial:
![2015-12-15_11-32-49](https://cloud.githubusercontent.com/assets/1765023/11808262/b0b88a12-a31f-11e5-91a8-143f49cdef1f.png)

**Comment by miyconst** [comment]
Yes. Thank you for finding this. The Launcher app was changed after tutorials were written.
