### ISSUE TITLE
Tutorial sample app 3 - step 3-2.A workspace without AppName

### ISSUE THREAD

**Issue by pluppplupp** [Starcounter/InvoiceDemo#55]
http://starcounter.io/tutorials/invoicedemo-part-3/3-2-run-invoicedemo-inside-launcher/

![2015-12-15_12-07-40](https://cloud.githubusercontent.com/assets/1765023/11811764/c5c103a4-a337-11e5-8a43-69008dd13cf9.png)

After completing the tasks of step 3-2 trying to launch the InvoiceDemo application inside the Launcher I get this error message.

Debugging is hard, since the error message doesn't say why or where to begin. Checking in the debug aid, we found that you need to put your static resources inside a folder below the wwwroot.

This structure will not work:
![2015-12-15_13-30-17](https://cloud.githubusercontent.com/assets/1765023/11811875/7dc0f1ee-a338-11e5-937d-7e69167eb62c.png)

But this will:
![2015-12-15_14-32-10](https://cloud.githubusercontent.com/assets/1765023/11811920/bb15b5ac-a338-11e5-93c9-7bfee9f30dcf.png)

Now the failing Url: "/sc/htmlmerger?StartCounter_InvoiceDemo1=/starcounter_invoicedemo1/LauncherWrapperPage.html" works and the response is correct. But I still get the "A workspace without AppName" error. I cannot run the demo app in the Launcher, only as a standalone.

I've debugged the Launcher application, it returns correct workspace and appname from ```static Response WrapInLauncher(Request req, String appName)```

The appname looks to be missing on model.workspaces[n]
![2015-12-15_15-52-56](https://cloud.githubusercontent.com/assets/1765023/11813895/0e2a3a1e-a344-11e5-9ed5-235ee2930b53.png)
making this if render the error message
![2015-12-15_15-53-10](https://cloud.githubusercontent.com/assets/1765023/11813902/1c3dac6c-a344-11e5-9f10-5401cc1a9858.png)

**Comment by pluppplupp** [comment]
The real problem was that the EXE (Assembly) in the VS.NET solution had a type-o. "Star(t)Counter". All the routes was correctly named "starcounter". And somewhere in starcounter the appname is taken from the executing assembly but often from the first part of the url. When these didn't match, this error ocurred.

**Comment by warpech** [comment]
This is fixed in https://github.com/StarcounterPrefabs/Launcher/issues/208
