### ISSUE TITLE
Tutorial Sample app 2 - Step 2-7. pupped-redirect - not found

### ISSUE THREAD

**Issue by diliger** [Starcounter/InvoiceDemo#58]
When I run the sample2 redirects don't work, probably because pupped-redirect not found.

Here is an error what i see in debug console:

![pupped-redirect - not found](https://cloud.githubusercontent.com/assets/15857369/12199841/3cdb5316-b62c-11e5-8181-5bb089660902.png)

сс @miyconst

**Comment by miyconst** [comment]
Thanks for reporting. You are probably using the latest nightly build, which has latest `puppet-redirect`.

In the latest `puppet-redirect` the `src` folder was removed. You can modify url to `puppet-redirect/puppet-redirect.html` to fix the issue.

@warpech should I update the tutorials or wait till we release next stable version?

**Comment by warpech** [comment]
@miyconst The tutorial should reflect the stable version that is linked on the Downloads page.

Meanwhile, could you add a sidenote saying that starting from Starcounter 2.1.x (put the relevant nightly version in x), the path to the file is `puppet-redirect/puppet-redirect.html`?

**Comment by miyconst** [comment]
Sure, I can do that.

**Comment by miyconst** [comment]
Added comments in sources and tutorials.
