### ISSUE TITLE
Tutorial Sample app 2 - Step 2-7. Delete New Invoice Error

### ISSUE THREAD

**Issue by diliger** [Starcounter/InvoiceDemo#59]
Start the application.

Follow New Invoice link and press Delete invoice.

I get this error:
![Delete New Invoice Error](https://cloud.githubusercontent.com/assets/15857369/12199968/0c040138-b62d-11e5-9739-ef3425c737ca.png)

cc @miyconst

**Comment by miyconst** [comment]
Could you please provide full exception text from Starcounter administrator log section?

**Comment by miyconst** [comment]
Seems like this is a duplicate of this issue: https://github.com/Starcounter/Starcounter/issues/2814

I will fix the tutorials with a workaround.

**Comment by miyconst** [comment]
Fixed. Updated tutorials.
