### ISSUE TITLE
Tutorial sample app 3 - step 3-3. Add styles

### ISSUE THREAD

**Issue by diliger** [Starcounter/InvoiceDemo#60]
Well, actually i got confused here.

First:
I should add styles to the InvoicesPage.html as tutorial says, but where to add?
As i got later, i should put it in the top, right before any existing html.

Second:
Why the url to the style.css contains a subfolder in the path? 
It's never mentioned that we should put the content of wwwroot folder to a subfolder with the same name as the project is.

Here is an image:
![Add styles piece](https://cloud.githubusercontent.com/assets/15857369/12203195/b649c716-b63e-11e5-8b46-0150f83c5a2a.png)

cc @miyconst

**Comment by miyconst** [comment]
Thanks for your feedback.

>I should add styles to the InvoicesPage.html as tutorial says, but where to add?
As i got later, i should put it in the top, right before any existing html.

For me the code snippet explains where to put the styles link - before the link to `puppet-redirect`.

> It's never mentioned that we should put the content of wwwroot folder to a subfolder with the same name as the project is.

Good point, I will update the tutorials.

**Comment by warpech** [comment]
Thanks for reporting!

> For me the code snippet explains where to put the styles link - before the link to puppet-redirect.

At this stage, there is no link to `puppet-redirect` either in that file.

I have added a clarification on top of http://starcounter.io/tutorials/invoicedemo-part-3/3-3-add-styles/

> > It's never mentioned that we should put the content of wwwroot folder to a subfolder with the same name as the project is.

> Good point, I will update the tutorials.

This is tracked in a separate issue https://github.com/Starcounter/InvoiceDemo/issues/27.

I will make all the InvoiceDemos (1, 2, 3) use `wwwroot/InvoiceDemo` for consistency.
