### ISSUE TITLE
Tutorial sample app 3 - step 3-8. People app pupped-redirect not found

### ISSUE THREAD

**Issue by diliger** [Starcounter/InvoiceDemo#61]
Cannot edit existing company or person.

Pupped-redirect not found.

![Pupped-redirect not found](https://cloud.githubusercontent.com/assets/15857369/12215148/59a6f078-b6c1-11e5-8e30-056f277a972b.png)

cc @miyconst

**Comment by warpech** [comment]
I will be fixing InvoiceDemo issues today, starting from most recent one (this one)

**Comment by warpech** [comment]
Fixed by releasing a new version of People (3.0.5). Changes were already made in December (https://github.com/StarcounterSamples/People/commit/fc4b13298d2a0c0e24551fb20b5843ff36171ae9) but were not released. 

Thanks for reporting!
