### ISSUE TITLE
Header is duplicated when running together with Launcher

### ISSUE THREAD

**Issue by joozek78** [Starcounter/InvoiceDemo#67]
1. Run Launcher and InvoiceDemo part 3 together
1. Go to localhost:8080
1. Click on InvoiceDemo icon twice
1. Header is duplicated (see attached image)
![image](https://cloud.githubusercontent.com/assets/6013217/15139015/c8bd1fd2-1693-11e6-81ae-1a8c3cd64607.png)

**Comment by warpech** [comment]
I'll investigate that. Thanks for reporting.

**Comment by miyconst** [comment]
I also have this issue with other apps, just didn't have enough time to report.

**Comment by warpech** [comment]
@tomalec could you please investigate this?

**Comment by tomalec** [comment]
@joozek78 @miyconst Did you used latest Launcher? I cannot reproduce it.

**Comment by miyconst** [comment]
Yes, for me it happened with latest Launcher, it will look for steps to reproduce when it happens again.

**Comment by tomalec** [comment]
Here is what I did
![double header](https://cloud.githubusercontent.com/assets/17435/15143615/e8e53ac6-16aa-11e6-88e9-6e35f2c00ebf.gif)
StarcounterSamples/Launcher@97e5ed886d
Starcounter/InvoiceDemo@0f2e23b456

**Comment by joozek78** [comment]
I used yesterday's Launcher, so probably fresh enough. After InvoiceDemo
loaded I clicked its icon on the left again and from then on I had
duplicated header. I can try looking for some more replication paths later.

**Comment by warpech** [comment]
Can you say what is the Starcounter version that you are using?

**Comment by joozek78** [comment]
Fresh nightly. 2.2.1.2069

**Comment by joozek78** [comment]
In today's Launcher the bug is fixed o_O

**Comment by tomalec** [comment]
I suspect I fixed it yesterday with https://github.com/StarcounterPrefabs/Launcher/commit/5dcabde1ae4346c3f8d6b34eb9a140fde5ef7757
